presence: Remove unused lambda captures
Fix clang-tidy errors:
```
../presence/anyof.cpp:141:22: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
../presence/anyof.cpp:145:23: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
```

Signed-off-by: Matt Spinler <spinler@us.ibm.com>
Change-Id: I6d8a48b57f7234e2c1ceaec57f5bcb96fa1d0c5d