control: Removed unused variables
Fix clang-tidy errors like:
```
../control/json/event.hpp:153:23: error: private field '_bus' is not used [-Werror,-Wunused-private-field]
```

Signed-off-by: Matt Spinler <spinler@us.ibm.com>
Change-Id: Ie57fbf73b16ce00b3eb67a0a0746f263ad333267