sensor-mon: Fix unused lambda capture warning
Fix:
```
../sensor-monitor/threshold_alarm_logger.cpp:135:39: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
  135 |                           [interface, this](const auto& object) {
```

Signed-off-by: Matt Spinler <spinler@us.ibm.com>
Change-Id: I47d5e772f5aef624f53959a98268857ac04660c5