sensor-mon: Remove unused variable
Fix clang-tidy error:
```
../sensor-monitor/threshold_alarm_logger.hpp:211:25: error: private field 'event' is not used [-Werror,-Wunused-private-field]
```

Signed-off-by: Matt Spinler <spinler@us.ibm.com>
Change-Id: I35ef3a74be5e1db36d39c6ffafbd11e5a784ba87