monitor: Removed unused variable
Fix clang-tidy error:
```
../monitor/fan.hpp:277:12: error: private field '_numFailedSensor' is not used [-Werror,-Wunused-private-field]
```

Signed-off-by: Matt Spinler <spinler@us.ibm.com>
Change-Id: I812c417d6c84adcf6e9045299e4705e8a58a4089