monitor: Remove unused lambda capture
Fix clang-tidy error:
```
../monitor/system.cpp:421:24: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
```

Signed-off-by: Matt Spinler <spinler@us.ibm.com>
Change-Id: I933eed9d132c4599ccefa250b5bd6e9b1774f4c6