control: Fix unused lambda captures
Fix clang-tidy errors like:
```
../control/json/actions/pcie_card_floors.cpp:55:39: error: lambda capture 'zone' is not used [-Werror,-Wunused-lambda-capture]
```

Change-Id: Ide52bb55acfcc364b0c40fc97a30705df3c2ebfc
Signed-off-by: Matt Spinler <spinler@us.ibm.com>